//! Auto-generated by examples/generate_pow7_vectors.rs
//! Do not edit by hand.

use alloc::vec::Vec;

pub struct PermuteTestVector {
    pub initial_state: [[u8; 32]; 3],
    pub final_state: [[u8; 32]; 3],
}

pub struct HashTestVector {
    pub input: [[u8; 32]; 2],
    pub output: [u8; 32],
}

pub mod fp {
    use super::*;

    pub fn permute() -> Vec<PermuteTestVector> {
        vec![]
    }

    pub fn hash() -> Vec<HashTestVector> {
        vec![]
    }
}

pub mod fq {
    use super::*;

    pub fn permute() -> Vec<PermuteTestVector> {
        vec![]
    }

    pub fn hash() -> Vec<HashTestVector> {
        vec![]
    }
}
