//! The Poseidon algebraic hash function.

#![no_std]

#[macro_use]
extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use core::convert::TryInto;
use core::fmt;
use core::iter;
use core::marker::PhantomData;

use group::ff::{Field, FromUniformBytes, PrimeField};

pub(crate) mod fp;
pub(crate) mod fq;
pub(crate) mod grain;
pub(crate) mod mds;

#[cfg(any(test, feature = "test-dependencies"))]
pub mod test_vectors_5t3;

mod p128pow5t3;
pub use p128pow5t3::P128Pow5T3;

pub(crate) mod fp_pow7;
pub(crate) mod fq_pow7;

#[cfg(any(test, feature = "test-dependencies"))]
pub mod test_vectors_7t3;

mod p128pow7t3;
use grain::SboxType;
pub use p128pow7t3::P128Pow7T3;

/// The type used to hold permutation state.
pub type State<F, const T: usize> = [F; T];

/// The type used to hold sponge rate.
pub(crate) type SpongeRate<F, const RATE: usize> = [Option<F>; RATE];

/// The type used to hold the MDS matrix and its inverse.
pub type Mds<F, const T: usize> = [[F; T]; T];

/// A specification for a Poseidon permutation.
pub trait Spec<F: Field, const T: usize, const RATE: usize>: fmt::Debug {
    /// The number of full rounds for this specification.
    ///
    /// This must be an even number.
    fn full_rounds() -> usize;

    /// The number of partial rounds for this specification.
    fn partial_rounds() -> usize;

    /// The S-box for this specification.
    fn sbox(val: F) -> F;

    /// Side-loaded index of the first correct and secure MDS that will be generated by
    /// the reference implementation.
    ///
    /// This is used by the default implementation of [`Spec::constants`]. If you are
    /// hard-coding the constants, you may leave this unimplemented.
    fn secure_mds() -> usize;

    /// Generates `(round_constants, mat_external, mat_internal, mat_internal_diag_m_1)`
    /// corresponding to this specification.
    ///
    /// For Poseidon2:
    /// - `mat_external`: Full MDS matrix used in external (full) rounds
    /// - `mat_internal`: Circulant matrix used in internal (partial) rounds  
    /// - `mat_internal_diag_m_1`: Diagonal elements minus 1 for optimized internal matrix multiplication
    ///
    /// For Poseidon v1 compatibility, `mat_internal` should equal `mat_external` and
    /// `mat_internal_diag_m_1` should be all zeros.
    fn constants() -> (Vec<[F; T]>, Mds<F, T>, Mds<F, T>, [F; T]);
}

/// Generates `(round_constants, mat_external, mat_internal, mat_internal_diag_m_1)`
/// corresponding to this specification.
///
/// This generates Poseidon v1 compatible constants where mat_internal == mat_external
/// (full MDS for all rounds). For true Poseidon2, use externally generated constants.
pub fn generate_constants<
    F: FromUniformBytes<64> + Ord,
    S: Spec<F, T, RATE>,
    const T: usize,
    const RATE: usize,
>() -> (Vec<[F; T]>, Mds<F, T>, Mds<F, T>, [F; T]) {
    let r_f = S::full_rounds();
    let r_p = S::partial_rounds();

    let mut grain = grain::Grain::new(SboxType::Pow, T as u16, r_f as u16, r_p as u16);

    let round_constants = (0..(r_f + r_p))
        .map(|_| {
            let mut rc_row = [F::ZERO; T];
            for (rc, value) in rc_row
                .iter_mut()
                .zip((0..T).map(|_| grain.next_field_element()))
            {
                *rc = value;
            }
            rc_row
        })
        .collect();

    let (mds, _mds_inv) = mds::generate_mds::<F, T>(&mut grain, S::secure_mds());

    // For Poseidon v1 compatibility: mat_internal = mat_external, diagonal elements = 0
    let mat_internal_diag_m_1 = [F::ZERO; T];

    (round_constants, mds, mds, mat_internal_diag_m_1)
}

/// Runs the Poseidon permutation on the given state.
///
/// Exposed for testing purposes only.
#[cfg(feature = "test-dependencies")]
pub fn test_only_permute<F: Field, S: Spec<F, T, RATE>, const T: usize, const RATE: usize>(
    state: &mut State<F, T>,
    mat_external: &Mds<F, T>,
    mat_internal: &Mds<F, T>,
    mat_internal_diag_m_1: &[F; T],
    round_constants: &[[F; T]],
) {
    permute::<F, S, T, RATE>(
        state,
        mat_external,
        mat_internal,
        mat_internal_diag_m_1,
        round_constants,
    );
}

/// Runs the Poseidon permutation on the given state.
pub fn permute<F: Field, S: Spec<F, T, RATE>, const T: usize, const RATE: usize>(
    state: &mut State<F, T>,
    mat_external: &Mds<F, T>,
    mat_internal: &Mds<F, T>,
    mat_internal_diag_m_1: &[F; T],
    round_constants: &[[F; T]],
) {
    debug_assert_eq!(
        round_constants.len(),
        S::full_rounds() + S::partial_rounds()
    );

    fn apply_matrix<F: Field, const T: usize>(state: &mut State<F, T>, matrix: &Mds<F, T>) {
        let mut new_state = [F::ZERO; T];
        #[allow(clippy::needless_range_loop)]
        for i in 0..T {
            for j in 0..T {
                new_state[i] += matrix[i][j] * state[j];
            }
        }
        *state = new_state;
    }

    fn apply_internal_matrix<F: Field, const T: usize>(
        state: &mut State<F, T>,
        matrix: &Mds<F, T>,
        diag_m_1: &[F; T],
    ) {
        if diag_m_1.iter().all(|coeff| bool::from(coeff.is_zero())) {
            apply_matrix(state, matrix);
            return;
        }

        #[cfg(debug_assertions)]
        {
            for i in 0..T {
                debug_assert_eq!(matrix[i][i], diag_m_1[i] + F::ONE);
                for j in 0..T {
                    if i != j {
                        debug_assert_eq!(matrix[i][j], F::ONE);
                    }
                }
            }
        }

        let mut sum = F::ZERO;
        for value in state.iter() {
            sum += *value;
        }

        let mut new_state = [F::ZERO; T];
        for (idx, word) in state.iter().enumerate() {
            new_state[idx] = diag_m_1[idx] * *word + sum;
        }

        *state = new_state;
    }

    // Poseidon2 applies an external linear layer before any S-box evaluations.
    apply_matrix(state, mat_external);

    let mut round_idx = 0usize;
    let half_full = S::full_rounds() / 2;
    let partial_pairs = S::partial_rounds() / 2;

    let apply_full_round = |state: &mut State<F, T>, round_constants: &[F; T]| {
        for (word, rc) in state.iter_mut().zip(round_constants.iter()) {
            *word = S::sbox(*word + *rc);
        }
    };

    // First half of the full rounds.
    for _ in 0..half_full {
        apply_full_round(state, &round_constants[round_idx]);
        apply_matrix(state, mat_external);
        round_idx += 1;
    }

    // Partial rounds are processed two at a time with the internal matrix.
    for _ in 0..partial_pairs {
        {
            for (idx, word) in state.iter_mut().enumerate() {
                *word += round_constants[round_idx][idx];
            }
            state[0] = S::sbox(state[0]);
            apply_internal_matrix(state, mat_internal, mat_internal_diag_m_1);
            round_idx += 1;
        }

        {
            for (idx, word) in state.iter_mut().enumerate() {
                *word += round_constants[round_idx][idx];
            }
            state[0] = S::sbox(state[0]);
            apply_internal_matrix(state, mat_internal, mat_internal_diag_m_1);
            round_idx += 1;
        }
    }

    // Second half of the full rounds.
    for _ in 0..half_full {
        apply_full_round(state, &round_constants[round_idx]);
        apply_matrix(state, mat_external);
        round_idx += 1;
    }

    debug_assert_eq!(round_idx, round_constants.len());
}

fn poseidon_sponge<F: Field, S: Spec<F, T, RATE>, const T: usize, const RATE: usize>(
    state: &mut State<F, T>,
    input: Option<&Absorbing<F, RATE>>,
    mat_external: &Mds<F, T>,
    mat_internal: &Mds<F, T>,
    mat_internal_diag_m_1: &[F; T],
    round_constants: &[[F; T]],
) -> Squeezing<F, RATE> {
    if let Some(Absorbing(input)) = input {
        // `Iterator::zip` short-circuits when one iterator completes, so this will only
        // mutate the rate portion of the state.
        for (word, value) in state.iter_mut().zip(input.iter()) {
            *word += value.expect("poseidon_sponge is called with a padded input");
        }
    }

    permute::<F, S, T, RATE>(
        state,
        mat_external,
        mat_internal,
        mat_internal_diag_m_1,
        round_constants,
    );

    let mut output = [None; RATE];
    for (word, value) in output.iter_mut().zip(state.iter()) {
        *word = Some(*value);
    }
    Squeezing(output)
}

mod private {
    pub trait SealedSpongeMode {}
    impl<F, const RATE: usize> SealedSpongeMode for super::Absorbing<F, RATE> {}
    impl<F, const RATE: usize> SealedSpongeMode for super::Squeezing<F, RATE> {}
}

/// The state of the `Sponge`.
pub trait SpongeMode: private::SealedSpongeMode {}

/// The absorbing state of the `Sponge`.
#[derive(Debug)]
pub struct Absorbing<F, const RATE: usize>(pub(crate) SpongeRate<F, RATE>);

/// The squeezing state of the `Sponge`.
#[derive(Debug)]
pub struct Squeezing<F, const RATE: usize>(pub(crate) SpongeRate<F, RATE>);

impl<F, const RATE: usize> SpongeMode for Absorbing<F, RATE> {}
impl<F, const RATE: usize> SpongeMode for Squeezing<F, RATE> {}

impl<F: fmt::Debug, const RATE: usize> Absorbing<F, RATE> {
    pub(crate) fn init_with(val: F) -> Self {
        let mut state = Self::init_empty();
        state.absorb(val).expect("state is not full");
        state
    }

    /// Initializes an empty sponge in the absorbing state.
    pub fn init_empty() -> Self {
        Self(
            (0..RATE)
                .map(|_| None)
                .collect::<Vec<_>>()
                .try_into()
                .unwrap(),
        )
    }
}

impl<F, const RATE: usize> Absorbing<F, RATE> {
    /// Attempts to absorb a value into the sponge state.
    ///
    /// Returns the value if it was not absorbed because the sponge is full.
    pub fn absorb(&mut self, value: F) -> Result<(), F> {
        for entry in self.0.iter_mut() {
            if entry.is_none() {
                *entry = Some(value);
                return Ok(());
            }
        }
        // Sponge is full.
        Err(value)
    }

    /// Exposes the inner state of the sponge.
    ///
    /// This is a low-level API, requiring a detailed understanding of this specific
    /// Poseidon implementation to use correctly and securely. It is exposed for use by
    /// the circuit implementation in `halo2_gadgets`, and may be removed from the public
    /// API if refactoring enables the circuit implementation to move into this crate.
    pub fn expose_inner(&self) -> &SpongeRate<F, RATE> {
        &self.0
    }
}

impl<F: fmt::Debug, const RATE: usize> Squeezing<F, RATE> {
    /// Initializes a full sponge in the squeezing state.
    ///
    /// This is a low-level API, requiring a detailed understanding of this specific
    /// Poseidon implementation to use correctly and securely. It is exposed for use by
    /// the circuit implementation in `halo2_gadgets`, and may be removed from the public
    /// API if refactoring enables the circuit implementation to move into this crate.
    pub fn init_full(vals: [F; RATE]) -> Self {
        Self(
            vals.into_iter()
                .map(Some)
                .collect::<Vec<_>>()
                .try_into()
                .unwrap(),
        )
    }
}

impl<F, const RATE: usize> Squeezing<F, RATE> {
    /// Attempts to squeeze a value from the sponge state.
    ///
    /// Returns `None` if the sponge is empty.
    pub fn squeeze(&mut self) -> Option<F> {
        for entry in self.0.iter_mut() {
            if let Some(inner) = entry.take() {
                return Some(inner);
            }
        }
        // Sponge is empty.
        None
    }
}

/// A Poseidon sponge.
pub(crate) struct Sponge<
    F: Field,
    S: Spec<F, T, RATE>,
    M: SpongeMode,
    const T: usize,
    const RATE: usize,
> {
    mode: M,
    state: State<F, T>,
    mat_external: Mds<F, T>,
    mat_internal: Mds<F, T>,
    mat_internal_diag_m_1: [F; T],
    round_constants: Vec<[F; T]>,
    _marker: PhantomData<S>,
}

impl<F: Field, S: Spec<F, T, RATE>, const T: usize, const RATE: usize>
    Sponge<F, S, Absorbing<F, RATE>, T, RATE>
{
    /// Constructs a new sponge for the given Poseidon specification.
    pub(crate) fn new(initial_capacity_element: F) -> Self {
        let (round_constants, mat_external, mat_internal, mat_internal_diag_m_1) = S::constants();

        let mode = Absorbing([None; RATE]);
        let mut state = [F::ZERO; T];
        state[RATE] = initial_capacity_element;

        Sponge {
            mode,
            state,
            mat_external,
            mat_internal,
            mat_internal_diag_m_1,
            round_constants,
            _marker: PhantomData::default(),
        }
    }

    /// Absorbs an element into the sponge.
    pub(crate) fn absorb(&mut self, value: F) {
        for entry in self.mode.0.iter_mut() {
            if entry.is_none() {
                *entry = Some(value);
                return;
            }
        }

        // We've already absorbed as many elements as we can
        let _ = poseidon_sponge::<F, S, T, RATE>(
            &mut self.state,
            Some(&self.mode),
            &self.mat_external,
            &self.mat_internal,
            &self.mat_internal_diag_m_1,
            &self.round_constants,
        );
        self.mode = Absorbing::init_with(value);
    }

    /// Transitions the sponge into its squeezing state.
    pub(crate) fn finish_absorbing(mut self) -> Sponge<F, S, Squeezing<F, RATE>, T, RATE> {
        let mode = poseidon_sponge::<F, S, T, RATE>(
            &mut self.state,
            Some(&self.mode),
            &self.mat_external,
            &self.mat_internal,
            &self.mat_internal_diag_m_1,
            &self.round_constants,
        );

        Sponge {
            mode,
            state: self.state,
            mat_external: self.mat_external,
            mat_internal: self.mat_internal,
            mat_internal_diag_m_1: self.mat_internal_diag_m_1,
            round_constants: self.round_constants,
            _marker: PhantomData::default(),
        }
    }
}

impl<F: Field, S: Spec<F, T, RATE>, const T: usize, const RATE: usize>
    Sponge<F, S, Squeezing<F, RATE>, T, RATE>
{
    /// Squeezes an element from the sponge.
    pub(crate) fn squeeze(&mut self) -> F {
        loop {
            for entry in self.mode.0.iter_mut() {
                if let Some(e) = entry.take() {
                    return e;
                }
            }

            // We've already squeezed out all available elements
            self.mode = poseidon_sponge::<F, S, T, RATE>(
                &mut self.state,
                None,
                &self.mat_external,
                &self.mat_internal,
                &self.mat_internal_diag_m_1,
                &self.round_constants,
            );
        }
    }
}

/// A domain in which a Poseidon hash function is being used.
pub trait Domain<F: Field, const RATE: usize> {
    /// Iterator that outputs padding field elements.
    type Padding: IntoIterator<Item = F>;

    /// The name of this domain, for debug formatting purposes.
    fn name() -> String;

    /// The initial capacity element, encoding this domain.
    fn initial_capacity_element() -> F;

    /// Returns the padding to be appended to the input.
    fn padding(input_len: usize) -> Self::Padding;
}

/// A Poseidon hash function used with constant input length.
///
/// Domain specified in [ePrint 2019/458 section 4.2](https://eprint.iacr.org/2019/458.pdf).
#[derive(Clone, Copy, Debug)]
pub struct ConstantLength<const L: usize>;

impl<F: PrimeField, const RATE: usize, const L: usize> Domain<F, RATE> for ConstantLength<L> {
    type Padding = iter::Take<iter::Repeat<F>>;

    fn name() -> String {
        format!("ConstantLength<{}>", L)
    }

    fn initial_capacity_element() -> F {
        // Capacity value is $length \cdot 2^64 + (o-1)$ where o is the output length.
        // We hard-code an output length of 1.
        F::from_u128((L as u128) << 64)
    }

    fn padding(input_len: usize) -> Self::Padding {
        assert_eq!(input_len, L);
        // For constant-input-length hashing, we pad the input with zeroes to a multiple
        // of RATE. On its own this would not be sponge-compliant padding, but the
        // Poseidon authors encode the constant length into the capacity element, ensuring
        // that inputs of different lengths do not share the same permutation.
        let k = (L + RATE - 1) / RATE;
        iter::repeat(F::ZERO).take(k * RATE - L)
    }
}

/// A Poseidon hash function, built around a sponge.
pub struct Hash<
    F: Field,
    S: Spec<F, T, RATE>,
    D: Domain<F, RATE>,
    const T: usize,
    const RATE: usize,
> {
    sponge: Sponge<F, S, Absorbing<F, RATE>, T, RATE>,
    _domain: PhantomData<D>,
}

impl<F: Field, S: Spec<F, T, RATE>, D: Domain<F, RATE>, const T: usize, const RATE: usize>
    fmt::Debug for Hash<F, S, D, T, RATE>
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Hash")
            .field("width", &T)
            .field("rate", &RATE)
            .field("R_F", &S::full_rounds())
            .field("R_P", &S::partial_rounds())
            .field("domain", &D::name())
            .finish()
    }
}

impl<F: Field, S: Spec<F, T, RATE>, D: Domain<F, RATE>, const T: usize, const RATE: usize>
    Hash<F, S, D, T, RATE>
{
    /// Initializes a new hasher.
    pub fn init() -> Self {
        Hash {
            sponge: Sponge::new(D::initial_capacity_element()),
            _domain: PhantomData::default(),
        }
    }
}

impl<F: PrimeField, S: Spec<F, T, RATE>, const T: usize, const RATE: usize, const L: usize>
    Hash<F, S, ConstantLength<L>, T, RATE>
{
    /// Hashes the given input.
    pub fn hash(mut self, message: [F; L]) -> F {
        for value in message
            .into_iter()
            .chain(<ConstantLength<L> as Domain<F, RATE>>::padding(L))
        {
            self.sponge.absorb(value);
        }
        self.sponge.finish_absorbing().squeeze()
    }
}

#[cfg(test)]
mod tests {
    use group::ff::PrimeField;
    use pasta_curves::pallas;

    use super::{permute, ConstantLength, Hash, P128Pow5T3 as OrchardNullifier, Spec};

    #[test]
    fn orchard_spec_equivalence() {
        let message = [pallas::Base::from(6), pallas::Base::from(42)];

        let (round_constants, mat_external, mat_internal, mat_internal_diag_m_1) =
            OrchardNullifier::constants();

        let hasher = Hash::<_, OrchardNullifier, ConstantLength<2>, 3, 2>::init();
        let result = hasher.hash(message);

        // The result should be equivalent to just directly applying the permutation and
        // taking the first state element as the output.
        let mut state = [message[0], message[1], pallas::Base::from_u128(2 << 64)];
        permute::<_, OrchardNullifier, 3, 2>(
            &mut state,
            &mat_external,
            &mat_internal,
            &mat_internal_diag_m_1,
            &round_constants,
        );
        assert_eq!(state[0], result);
    }
}
