use ff::PrimeField;
use halo2_poseidon2::{permute, ConstantLength, Hash, P128Pow5T3, Spec};
use pasta_curves::{pallas::Base as Fp, vesta::Base as Fq};

fn main() {
    println!("//! Auto-generated by examples/generate_poseidon2_vectors.rs");
    println!("//! Do not edit by hand.");
    println!();
    println!("use alloc::vec::Vec;");
    println!();
    println!("pub struct PermuteTestVector {{");
    println!("    pub initial_state: [[u8; 32]; 3],");
    println!("    pub final_state: [[u8; 32]; 3],");
    println!("}}");
    println!();
    println!("pub struct HashTestVector {{");
    println!("    pub input: [[u8; 32]; 2],");
    println!("    pub output: [u8; 32],");
    println!("}}");
    println!();

    print_fp_module();
    print_fq_module();
}

fn print_fp_module() {
    const PERMUTE_INPUTS: [[u64; 3]; 4] = [[0, 1, 2], [5, 8, 13], [21, 34, 55], [89, 144, 233]];

    const HASH_INPUTS: [[u64; 2]; 4] = [[0, 0], [1, 2], [3, 5], [8, 13]];

    let (round_constants, mat_external, mat_internal, mat_internal_diag_m_1) =
        P128Pow5T3::constants();

    println!("pub mod fp {{");
    println!("    use super::*;");
    println!();
    println!("    pub fn permute() -> Vec<PermuteTestVector> {{");
    println!("        use PermuteTestVector as TestVector;");
    println!("        vec![");

    for input in PERMUTE_INPUTS {
        let mut state = [Fp::from(input[0]), Fp::from(input[1]), Fp::from(input[2])];
        let mut initial_bytes = [[0u8; 32]; 3];
        for (idx, value) in state.iter().enumerate() {
            initial_bytes[idx] = to_bytes(*value);
        }

        permute::<Fp, P128Pow5T3, 3, 2>(
            &mut state,
            &mat_external,
            &mat_internal,
            &mat_internal_diag_m_1,
            &round_constants,
        );
        let mut final_bytes = [[0u8; 32]; 3];
        for (idx, value) in state.iter().enumerate() {
            final_bytes[idx] = to_bytes(*value);
        }

        println!("            TestVector {{");
        println!("                initial_state: [");
        for element in &initial_bytes {
            println!("                    [");
            print_byte_lines(24, element);
            println!("                    ],");
        }
        println!("                ],");
        println!("                final_state: [");
        for element in &final_bytes {
            println!("                    [");
            print_byte_lines(24, element);
            println!("                    ],");
        }
        println!("                ],");
        println!("            }},");
    }

    println!("        ]");
    println!("    }}");
    println!();
    println!("    pub fn hash() -> Vec<HashTestVector> {{");
    println!("        use HashTestVector as TestVector;");
    println!("        vec![");

    for input in HASH_INPUTS {
        let message = [Fp::from(input[0]), Fp::from(input[1])];
        let mut message_bytes = [[0u8; 32]; 2];
        for (idx, value) in message.iter().enumerate() {
            message_bytes[idx] = to_bytes(*value);
        }

        let output = Hash::<Fp, P128Pow5T3, ConstantLength<2>, 3, 2>::init().hash(message);
        let output_bytes = to_bytes(output);

        println!("            TestVector {{");
        println!("                input: [");
        for element in &message_bytes {
            println!("                    [");
            print_byte_lines(24, element);
            println!("                    ],");
        }
        println!("                ],");
        println!("                output: [");
        print_byte_lines(20, &output_bytes);
        println!("                ],");
        println!("            }},");
    }

    println!("        ]");
    println!("    }}");
    println!("}}");
}

fn print_fq_module() {
    const PERMUTE_INPUTS: [[u64; 3]; 4] = [[0, 1, 2], [3, 5, 7], [11, 13, 17], [19, 23, 29]];

    const HASH_INPUTS: [[u64; 2]; 4] = [[0, 0], [2, 3], [5, 7], [11, 13]];

    let (round_constants, mat_external, mat_internal, mat_internal_diag_m_1) =
        P128Pow5T3::constants();

    println!();
    println!("pub mod fq {{");
    println!("    use super::*;");
    println!();
    println!("    pub fn permute() -> Vec<PermuteTestVector> {{");
    println!("        use PermuteTestVector as TestVector;");
    println!("        vec![");

    for input in PERMUTE_INPUTS {
        let mut state = [Fq::from(input[0]), Fq::from(input[1]), Fq::from(input[2])];
        let mut initial_bytes = [[0u8; 32]; 3];
        for (idx, value) in state.iter().enumerate() {
            initial_bytes[idx] = to_bytes(*value);
        }

        permute::<Fq, P128Pow5T3, 3, 2>(
            &mut state,
            &mat_external,
            &mat_internal,
            &mat_internal_diag_m_1,
            &round_constants,
        );
        let mut final_bytes = [[0u8; 32]; 3];
        for (idx, value) in state.iter().enumerate() {
            final_bytes[idx] = to_bytes(*value);
        }

        println!("            TestVector {{");
        println!("                initial_state: [");
        for element in &initial_bytes {
            println!("                    [");
            print_byte_lines(24, element);
            println!("                    ],");
        }
        println!("                ],");
        println!("                final_state: [");
        for element in &final_bytes {
            println!("                    [");
            print_byte_lines(24, element);
            println!("                    ],");
        }
        println!("                ],");
        println!("            }},");
    }

    println!("        ]");
    println!("    }}");
    println!();
    println!("    pub fn hash() -> Vec<HashTestVector> {{");
    println!("        use HashTestVector as TestVector;");
    println!("        vec![");

    for input in HASH_INPUTS {
        let message = [Fq::from(input[0]), Fq::from(input[1])];
        let mut message_bytes = [[0u8; 32]; 2];
        for (idx, value) in message.iter().enumerate() {
            message_bytes[idx] = to_bytes(*value);
        }

        let output = Hash::<Fq, P128Pow5T3, ConstantLength<2>, 3, 2>::init().hash(message);
        let output_bytes = to_bytes(output);

        println!("            TestVector {{");
        println!("                input: [");
        for element in &message_bytes {
            println!("                    [");
            print_byte_lines(24, element);
            println!("                    ],");
        }
        println!("                ],");
        println!("                output: [");
        print_byte_lines(20, &output_bytes);
        println!("                ],");
        println!("            }},");
    }

    println!("        ]");
    println!("    }}");
    println!("}}");
}

fn print_byte_lines(indent: usize, bytes: &[u8; 32]) {
    let indent_str = " ".repeat(indent);
    for chunk in bytes.chunks(16) {
        let mut line = indent_str.clone();
        for byte in chunk {
            line.push_str(&format!("0x{:02x}, ", byte));
        }
        println!("{}", line);
    }
}

fn to_bytes<F: PrimeField>(value: F) -> [u8; 32] {
    let repr = value.to_repr();
    let mut bytes = [0u8; 32];
    bytes.copy_from_slice(repr.as_ref());
    bytes
}
